-- This file is QUARANTINED --

-- I REPEAT DO NOT EDIT THIS FILE RONALD SIN--

--just make it so player can walk, moves and will rotate towards the player mouse

function createPlayer()

	local player = {}

	player.x = 973
	player.y = 1091
	player.r = 0

	-- rotate player model to mouse
	function player.rotate()

		player.rotation = (math.atan2(camera.getMouseY() - player.y, camera.getMouseX() - player.x) + (math.pi / 2))

	end

	function player.update(dt)

		player.rotate()

	end

	function player.draw()

	end

	return player
end
